### ISSUE TITLE
Cannot login to Live ID

### ISSUE THREAD

**Issue by swbuehler** [OneNoteDev/OneNoteAPISamplePHP#1]
I’m getting the following error consistently when the signing page pops up:

Microsoft account

We're unable to complete your request
Microsoft account is experiencing technical problems. Please try again later.

**Comment by Velojet** [comment]
Just for the record: I had the same issue and tried to resolve it as suggested by using the GitHub cloned files, rather than the zipped ones. No joy.
Eventually resolved it by setting Filezilla's transfer mode to 'Binary' to preserve the CRLFs.
(BTW, excellent sample code - thanks!)

**Comment by codeye** [comment]
This is still a problem and noted under <b>Known Issues</b>.
I'm editing files under TextWrangler for OSX and fell into the trap of not adjusting line feeds from linux (LR) to Windows (CRLF)(option is at the bottom of TextWrangler). Just for anyone editing outside github.
Looking in a hex editor showed the difference in the postdata '0A' in my case instead of '0D0A' (expected by the API), the payload was reduced in size by the missing '0D' bytes.
